services:
  - type: web
    name: mason-avenue-firearms
    env: node
    region: florida
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: mason-avenue-firearms
          envVarKey: RENDER_EXTERNAL_URL
      - key: AWS_BUCKET_NAME
        sync: false
      - key: AWS_FOLDER_PREFIX
        sync: false
      - key: AWS_REGION
        value: us-west-2
      - key: AWS_PROFILE
        value: hosted_storage
      - key: ABACUSAI_API_KEY
        sync: false
      - key: WEB_APP_ID
        sync: false
      - key: NOTIF_ID_SELL_FIREARM_SUBMISSION
        sync: false
      - key: NOTIF_ID_ITEM_REQUEST_SUBMISSION
        sync: false
      - key: NOTIF_ID_PAWN_LOAN_REQUEST
        sync: false
      - key: NOTIFICATION_RECIPIENT_EMAIL
        sync: false
