import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const inventoryItems = [
  // ===================== FIREARMS =====================
  {
    id: 'item-glock19',
    name: 'Glock 19 Gen 5',
    brand: 'Glock',
    price: 549.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'New',
    description: 'The Glock 19 Gen 5 is the most versatile and popular compact 9mm in the world. Features the Marksman Barrel for improved accuracy, ambidextrous slide stop lever, and flared mag-well. Perfect for concealed carry and home defense.',
    imageUrl: 'https://cdn.abacus.ai/images/97f5d3bc-5c7c-4e83-823e-4a51cd211a3f.png',
    caliber: '9mm',
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 147,
    sku: 'GLK-19G5-001',
  },
  {
    id: 'item-sw-shield',
    name: 'Smith & Wesson M&P Shield Plus',
    brand: 'Smith & Wesson',
    price: 479.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'New',
    description: 'The M&P Shield Plus features a 13+1 capacity in a micro-compact frame. Enhanced trigger, flat face design, and optimal 18-degree grip angle. Ideal everyday carry pistol.',
    imageUrl: 'https://cdn.abacus.ai/images/f5aee54d-9c52-42d9-9ef7-03221df7e1d6.png',
    caliber: '9mm',
    tag: 'just_in',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 89,
    sku: 'SW-SHLD-002',
  },
  {
    id: 'item-sig-p320',
    name: 'SIG Sauer P320 X-Carry',
    brand: 'SIG Sauer',
    price: 649.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'Like New',
    description: 'The P320 X-Carry features a modular polymer X-series grip, flat trigger, and optic-ready slide. Military-proven reliability with the accuracy SIG is known for.',
    imageUrl: 'https://cdn.abacus.ai/images/52143ffa-c0ef-4f89-a98f-6cc417ac5521.png',
    caliber: '9mm',
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 203,
    sku: 'SIG-P320-003',
  },
  {
    id: 'item-hellcat',
    name: 'Springfield Hellcat Pro',
    brand: 'Springfield Armory',
    price: 599.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'New',
    description: 'The Hellcat Pro brings 15+1 capacity in a concealable package. Features Adaptive Grip Texture, U-Dot sight system, and optics-ready slide. The ultimate carry gun.',
    imageUrl: 'https://cdn.abacus.ai/images/d1b299b0-b49d-453a-ba13-a5d07bbdd1ea.png',
    caliber: '9mm',
    tag: 'just_in',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 67,
    sku: 'SPR-HCP-004',
  },
  {
    id: 'item-ruger-gp100',
    name: 'Ruger GP100 .357 Magnum',
    brand: 'Ruger',
    price: 799.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'Excellent',
    description: 'The legendary GP100 revolver in .357 Magnum. Triple-locking cylinder, cushioned rubber grip, and 6-inch barrel. Built to handle thousands of rounds of full-power magnum ammunition.',
    imageUrl: 'https://cdn.abacus.ai/images/444564c2-d238-492d-9eb5-baded724a908.png',
    caliber: '.357 Magnum',
    tag: 'rare',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 312,
    sku: 'RGR-GP100-005',
  },
  {
    id: 'item-dd-ar15',
    name: 'Daniel Defense DDM4 V7',
    brand: 'Daniel Defense',
    price: 1899.99,
    department: 'firearms',
    category: 'rifle',
    condition: 'New',
    description: 'The DDM4 V7 is the gold standard in AR-15 rifles. Cold hammer forged barrel, M-LOK rail system, and mil-spec+ components throughout. Professional grade performance.',
    imageUrl: 'https://cdn.abacus.ai/images/b9b64af8-c2ec-4d6c-9069-3d9b5fc3fe94.png',
    caliber: '5.56 NATO',
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 456,
    sku: 'DD-V7-006',
  },
  {
    id: 'item-rem870',
    name: 'Remington 870 Express Tactical',
    brand: 'Remington',
    price: 449.99,
    department: 'firearms',
    category: 'shotgun',
    condition: 'Good',
    description: 'The most trusted pump-action shotgun in the world. 18.5-inch barrel, 6+1 capacity, tactical stock. Over 11 million produced — proven reliability for home defense.',
    imageUrl: 'https://cdn.abacus.ai/images/a944d1a6-abc8-43e7-85e8-957e4e03ef77.png',
    caliber: '12 Gauge',
    tag: null,
    status: 'available',
    inventoryStatus: 'available_to_order',
    featured: false,
    views: 98,
    sku: 'REM-870-007',
  },
  {
    id: 'item-mossberg500',
    name: 'Mossberg 500 Persuader',
    brand: 'Mossberg',
    price: 399.99,
    department: 'firearms',
    category: 'shotgun',
    condition: 'New',
    description: 'The Mossberg 500 Persuader is a purpose-built home defense shotgun. 20-inch barrel, 7+1 capacity, dual extractors, and anti-jam elevator. Mil-spec heavy wall barrel.',
    imageUrl: 'https://cdn.abacus.ai/images/b9c11ff2-c3dc-4c82-abed-1d40fdc3128d.png',
    caliber: '12 Gauge',
    tag: 'just_in',
    status: 'available',
    inventoryStatus: 'available_to_order',
    featured: true,
    views: 54,
    sku: 'MOS-500-008',
  },
  {
    id: 'item-henry',
    name: 'Henry Big Boy Classic .44 Mag',
    brand: 'Henry',
    price: 949.99,
    department: 'firearms',
    category: 'rifle',
    condition: 'Like New',
    description: 'American-made lever action perfection. Brass receiver, American walnut stock, 10-round capacity. Smooth as silk lever action with Henry\'s legendary fit and finish.',
    imageUrl: 'https://cdn.abacus.ai/images/64247fb0-60ee-466f-8969-ffaee28fc189.png',
    caliber: '.44 Magnum',
    tag: 'rare',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 278,
    sku: 'HNR-BB44-009',
  },
  {
    id: 'item-taurus-g3c',
    name: 'Taurus G3C',
    brand: 'Taurus',
    price: 249.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'New',
    description: 'Incredible value in a full-featured compact 9mm. 12+1 capacity, re-strike capability, and Taurus Security System. Best budget-friendly carry option on the market.',
    imageUrl: 'https://cdn.abacus.ai/images/576445c4-4dce-4b47-acea-8f5da682675b.png',
    caliber: '9mm',
    tag: null,
    status: 'available',
    inventoryStatus: 'available_to_order',
    featured: false,
    views: 45,
    sku: 'TAU-G3C-010',
  },
  {
    id: 'item-cz75',
    name: 'CZ 75 B',
    brand: 'CZ',
    price: 629.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'Excellent',
    description: 'The CZ 75 B is one of the finest 9mm pistols ever made. All-steel construction, 16+1 capacity, and legendary accuracy. Favored by competitive shooters worldwide.',
    imageUrl: 'https://cdn.abacus.ai/images/cf1f718b-393d-4a26-a705-67055de0b8ea.png',
    caliber: '9mm',
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'sourced',
    featured: true,
    views: 189,
    sku: 'CZ-75B-011',
  },
  {
    id: 'item-beretta',
    name: 'Beretta 92FS',
    brand: 'Beretta',
    price: 699.99,
    department: 'firearms',
    category: 'handgun',
    condition: 'Like New',
    description: 'The legendary Beretta 92FS — standard issue sidearm for the U.S. Military for over 30 years. Open-slide design, 15+1 capacity, and unmatched reliability in any condition.',
    imageUrl: 'https://cdn.abacus.ai/images/497e8945-67a1-408a-8bcc-ae05e8670b2f.png',
    caliber: '9mm',
    tag: null,
    status: 'sold',
    inventoryStatus: 'in_stock',
    featured: false,
    views: 567,
    sku: 'BER-92FS-012',
  },
  // ===================== JEWELRY =====================
  {
    id: 'item-rolex-sub',
    name: 'Rolex Submariner Date 41mm',
    brand: 'Rolex',
    price: 12499.99,
    department: 'jewelry',
    category: 'watches',
    condition: 'Excellent',
    description: 'The iconic Rolex Submariner Date in Oystersteel with a black Cerachrom bezel. 41mm case, caliber 3235 movement, waterproof to 300m. Box and papers included. A true investment timepiece.',
    imageUrl: '/products/jewelry-1.jpg',
    caliber: null,
    tag: 'rare',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 234,
    sku: 'JWL-ROLEX-001',
  },
  {
    id: 'item-cuban-chain',
    name: '14K Gold Cuban Link Chain 24\"',
    brand: 'Custom',
    price: 2899.99,
    department: 'jewelry',
    category: 'chains & necklaces',
    condition: 'Like New',
    description: 'Heavy 14K solid gold Cuban link chain, 24 inches, 8mm width. Lobster clasp. Weighs approximately 85 grams. Stunning shine and craftsmanship.',
    imageUrl: '/products/jewelry-2.jpg',
    caliber: null,
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 156,
    sku: 'JWL-CUBAN-002',
  },
  {
    id: 'item-diamond-ring',
    name: '2ct Diamond Solitaire Engagement Ring',
    brand: 'Tiffany & Co.',
    price: 8999.99,
    department: 'jewelry',
    category: 'rings',
    condition: 'Excellent',
    description: '2 carat round brilliant diamond solitaire set in platinum. VS1 clarity, F color. Tiffany setting with original box and GIA certification.',
    imageUrl: '/products/jewelry-3.jpg',
    caliber: null,
    tag: 'rare',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 312,
    sku: 'JWL-DRING-003',
  },
  {
    id: 'item-diamond-earrings',
    name: '1ct TW Diamond Stud Earrings',
    brand: 'David Yurman',
    price: 1599.99,
    department: 'jewelry',
    category: 'earrings',
    condition: 'New',
    description: '1 carat total weight diamond stud earrings in 14K white gold. Round brilliant cut, I color, SI1 clarity. Classic and elegant everyday luxury.',
    imageUrl: '/products/jewelry-4.jpg',
    caliber: null,
    tag: 'just_in',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 89,
    sku: 'JWL-EARR-004',
  },
  // ===================== ELECTRONICS =====================
  {
    id: 'item-macbook-pro',
    name: 'MacBook Pro 16\" M3 Pro',
    brand: 'Apple',
    price: 1899.99,
    department: 'electronics',
    category: 'laptops',
    condition: 'Like New',
    description: 'Apple MacBook Pro 16-inch with M3 Pro chip, 18GB RAM, 512GB SSD. Space Black finish. Battery cycle count under 50. Includes charger and original box.',
    imageUrl: '/products/electronics-1.jpg',
    caliber: null,
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 187,
    sku: 'ELC-MBP-001',
  },
  {
    id: 'item-ps5',
    name: 'PlayStation 5 Console Bundle',
    brand: 'Sony',
    price: 449.99,
    department: 'electronics',
    category: 'gaming',
    condition: 'Like New',
    description: 'PS5 disc edition with 2 DualSense controllers and 3 games included. Ultra-high speed SSD, 4K gaming, ray tracing. Original box and all cables included.',
    imageUrl: '/products/electronics-2.jpg',
    caliber: null,
    tag: 'just_in',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 134,
    sku: 'ELC-PS5-002',
  },
  {
    id: 'item-iphone15',
    name: 'iPhone 15 Pro Max 256GB',
    brand: 'Apple',
    price: 899.99,
    department: 'electronics',
    category: 'phones',
    condition: 'Excellent',
    description: 'iPhone 15 Pro Max in Natural Titanium. 256GB storage. A17 Pro chip. Battery health at 96%. No scratches, includes case and charger. Carrier unlocked.',
    imageUrl: '/products/electronics-3.jpg',
    caliber: null,
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: false,
    views: 245,
    sku: 'ELC-IPH15-003',
  },
  {
    id: 'item-bose-qc',
    name: 'Bose QuietComfort Ultra Headphones',
    brand: 'Bose',
    price: 279.99,
    department: 'electronics',
    category: 'audio',
    condition: 'New',
    description: 'Bose QuietComfort Ultra with world-class noise cancellation and Immersive Audio. CustomTune sound calibration, 24-hour battery life. Sealed in original packaging.',
    imageUrl: '/products/electronics-4.jpg',
    caliber: null,
    tag: null,
    status: 'available',
    inventoryStatus: 'available_to_order',
    featured: false,
    views: 67,
    sku: 'ELC-BOSE-004',
  },
  // ===================== TOOLS =====================
  {
    id: 'item-dewalt-drill',
    name: 'DeWalt 20V MAX XR Hammer Drill Kit',
    brand: 'DeWalt',
    price: 249.99,
    department: 'tools',
    category: 'power tools',
    condition: 'New',
    description: 'DeWalt DCD998W1 20V MAX XR brushless hammer drill/driver kit. 3-speed settings, 2,250 RPM, 38,250 BPM. Includes 2 batteries, charger, and hard case.',
    imageUrl: '/products/tools-1.jpg',
    caliber: null,
    tag: 'just_in',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 78,
    sku: 'TLS-DW-001',
  },
  {
    id: 'item-milwaukee-wrench',
    name: 'Milwaukee M18 FUEL Impact Wrench',
    brand: 'Milwaukee',
    price: 349.99,
    department: 'tools',
    category: 'power tools',
    condition: 'Like New',
    description: 'Milwaukee 2767-20 M18 FUEL High Torque 1/2" impact wrench with friction ring. 1,000 ft-lbs of fastening torque and 1,400 ft-lbs of nut-busting torque.',
    imageUrl: '/products/tools-2.jpg',
    caliber: null,
    tag: 'hot',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 112,
    sku: 'TLS-MIL-002',
  },
  {
    id: 'item-snapon-set',
    name: 'Snap-on 230pc Master Mechanic Set',
    brand: 'Snap-on',
    price: 1499.99,
    department: 'tools',
    category: 'tool sets',
    condition: 'Excellent',
    description: '230-piece Snap-on master mechanic tool set. Includes ratchets, sockets, wrenches, screwdrivers, and pliers in a roll cab. Professional-grade chrome vanadium steel.',
    imageUrl: '/products/tools-3.jpg',
    caliber: null,
    tag: 'rare',
    status: 'available',
    inventoryStatus: 'in_stock',
    featured: true,
    views: 198,
    sku: 'TLS-SNAP-003',
  },
  {
    id: 'item-husqvarna-saw',
    name: 'Husqvarna 460 Rancher 24\" Chainsaw',
    brand: 'Husqvarna',
    price: 549.99,
    department: 'tools',
    category: 'outdoor equipment',
    condition: 'Good',
    description: 'Husqvarna 460 Rancher with 24-inch bar. 60.3cc engine, X-Torq technology for lower fuel consumption and reduced emissions. Smart Start and air injection for easy maintenance.',
    imageUrl: '/products/tools-4.jpg',
    caliber: null,
    tag: null,
    status: 'available',
    inventoryStatus: 'available_to_order',
    featured: false,
    views: 45,
    sku: 'TLS-HUSQ-004',
  },
];

async function main() {
  const hashedPassword = await bcrypt.hash('johndoe123', 10);
  await prisma.user.upsert({
    where: { email: 'john@doe.com' },
    update: {},
    create: {
      email: 'john@doe.com',
      name: 'Admin',
      password: hashedPassword,
      role: 'admin',
    },
  });

  for (const item of inventoryItems) {
    await prisma.inventoryItem.upsert({
      where: { id: item.id },
      update: item,
      create: item,
    });
  }

  console.log('Seeded successfully');
}

main()
  .catch((e: any) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
